### ISSUE TITLE
Chaning Background Image from Drupal UI

### ISSUE THREAD

**Issue by itsdarrylnorris** [zetagraph/monoset#1]
## Problem/Motiviation

I do not see the ability of changing the background from the Drupal UI.
## Solution:

Provide the ability of uploading an image in configuration page of the theme, which is at `admin/appearance/settings/monoset`

**Comment by zetagraph** [comment]
@darol100 I am leaning toward keeping this theme pretty simple and customizing the backgrounds through css. If you are interested in adding this feature / setting config, it would be cool, otherwise I am leaving it as is for now.
