### ISSUE TITLE
Where is stylesguide directory

### ISSUE THREAD

**Issue by lsolesen** [zetagraph/monoset#14]
In the README file this sentence is present "Styleguide files are generated on running default "gulp" command inside the theme's "styleguide" directory."

However, I cannot find that directory anywhere?

**Comment by zetagraph** [comment]
@lsolesen the directory is generated dynamically if the styleguide gulp task is set up and run. The task is commented in the default theme gulp.js file. You can learn about styleguide stuff here: https://github.com/SC5/sc5-styleguide
