### ISSUE TITLE
themes/monoset/scripts/vendor/svg-injector.map.js not found (404 error)

### ISSUE THREAD

**Issue by itamair** [zetagraph/monoset#16]
at the first activation the console throws the error highlighted in the title.
It goes away refactoring (to //# sourceMappingURL=svg-injector.min.js) the last (commented) code row in the themes/monoset/scripts/vendor/svg-injector.min.js

I tested this theme on a testing Drupal 8 installation, with just the Article Content Type setup, and nothing is shown: neither Theme fonts. I downloaded all the dependencies (with npm install ...).
Am I doing something wrong?

**Comment by zetagraph** [comment]
@itamair not sure about the source mapping error, can't reproduce it locally, it also doesn't show up here: http://monoset.subtleshift.net.

Content of the blocks and home page sections are not part of the theme as those are generate by the user. If you want the same content you can copy it from the source code.
