### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by ghost** [zetagraph/monoset#18]
hello, 

I had installed `monoset` theme, but I have several problems with it and I hope you help me fix it.
1. after

``` sh
sudo npm install -g browsersync gulp
sudo npm install
```

and copying to `themes` directory, enabling them in `drupal` settings I had create a  new test post - and here there are several visual issues
![selection_005](https://cloud.githubusercontent.com/assets/13286493/13683065/d2416958-e715-11e5-902d-30a15d599477.png)
1. `gulp` command launch browser sync, but nothing is displayed (blank screen).

**Comment by zetagraph** [comment]
make sure you have things in the right regions
