### ISSUE TITLE
SVG images path question or NPM package issue

### ISSUE THREAD

**Issue by mixplex** [zetagraph/monoset#19]
Hello

I am interested in learning about your theme but when I install it, my browser using browsersync cant find these images: 

/themes/monoset/icons/chevron-up.svg
/themes/monoset/icons/twitter.svg

on the sub-page: /themes/monoset/logo.svg

I also had some warnings after npm-install.  I thought that might be the issue so I ran 
npm install svg-injector

I tried changing the path in page.html.twig and can browse to the files but the template can't output it.

I tried installing the theme both in the drupal root/themes/contrib directory and in my multsites directory.

Any help would be appreciated.  Thank you.

**Comment by mixplex** [comment]
I tried changing the path with {{ base_path ~ directory }}  but still cant get any image to load after the footer section completes in page.html.twig

**Comment by mixplex** [comment]
I chose to add 'scroll to top' module and will work with blocks.  I like how you did this theme and appreciated your video too.

**Comment by mixplex** [comment]
I got it figured out.  I just added a logo where it wanted to be put, above the images directory.

**Comment by zetagraph** [comment]
@mixplex glad you were able to figure it out. Sorry for not getting back to you, I am not able to offer any support at this time.
