### ISSUE TITLE
hgroup has now been removed from the HTML5 specification

### ISSUE THREAD

**Issue by itsdarrylnorris** [zetagraph/monoset#2]
## Problem/Motivation

Update 16th April, 2013. hgroup has now been removed from the HTML5 specification. We are working on an article to help guide authors on which markup patterns they should use instead.
http://html5doctor.com/the-hgroup-element/
## Solution:

I believe we should remove the hgroup from this project since HTML5 is not longer supported.

**Comment by zetagraph** [comment]
hgroup has been removed: https://github.com/zetagraph/monoset/commit/99a7f83c95d535d64d161c001c090c7c4c0412ca
