### ISSUE TITLE
gulp-sass install version issue in package.json

### ISSUE THREAD

**Issue by nco71** [zetagraph/monoset#23]
Hi , thank you for sharing this great and inspiring theme

I couldn't install gulp-sass 

in the log I got 

Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node":

so the url of this version of gulp-sass does not exist

running on docker latest version of node:alpine

node v8.4.0

I changed the version of gulp-sass from 2.1.0 to 3.1.0 in package.json and it solved the issue.

Maybe that is worth updating in the repository .. if other people have the same issued.

**Comment by zetagraph** [comment]
Hi @nco71  It's been a while since the node packages were updated. In any case, I just updated few of them here: https://github.com/zetagraph/monoset/commit/efce4552d087a92107e1449f8b75b0b6f698b733

Thanks for trying the theme and pointing this out.

**Comment by nco71** [comment]
Thank you for your quick reply.

new version of package.json working fine for me
