### ISSUE TITLE
Front Page for site builders.

### ISSUE THREAD

**Issue by itsdarrylnorris** [zetagraph/monoset#4]
**Problem/Motivation**

Every element on the front page is been hard-core into the theme. A site builder without any theming experience would not be able to modify this theme because everything is on the template.

**Solution**

We need to set these elements into blocks. After we move all these parts into If the block is not enable this should show empty. This would make life easier for site builder to manage the site without going to the template. Right now, if you install D8 installation and enable this theme it would show every single block that is been override on the template.

**Comment by zetagraph** [comment]
@darol100 block's content is not included or hardcoded into the theme. I am only specifying the regions and outputting them in page.html.twig. Content as shown here: http://subtleshift.net/ is not part of the theme, although it can be copied into blocks / regions if chosen to.
