### ISSUE TITLE
Theme doesn't work on Drupal 8 RC

### ISSUE THREAD

**Issue by yookoala** [zetagraph/monoset#8]
I did a fresh install of master branch on Drupal 8 RC2. The theme installed successful but the styles are not there. The HTML source shows no CSS nor script references. The page just appears as a blank skeleton.

It seems that somewhere between beta and RC, the template variable structure changed.

Need to revise the twig templates and adapt the changes.

**Comment by zetagraph** [comment]
Yes it needs few updates for sure. Will be looking into it soon. Thanks for pointing that out.
